source 'https://rubygems.org'

gem 'capybara', '~> 2.12'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'thor'
gem 'rspec'
gem 'mail'
gem 'site_prism', '~> 2.13'
gem 'require_all'
gem 'pry-rescue'
gem 'waitutil'
gem 'activesupport'
gem 'pry-stack_explorer'
gem 'colorize'
gem 'awesome_print'
gem 'webdrivers'
